# Generated by Django 5.1.6 on 2025-03-14 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_booking_date_booking_service_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='destination',
        ),
        migrations.AddField(
            model_name='booking',
            name='return_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='vehicle',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='core.vehicle'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicle',
            name='number_plate',
            field=models.CharField(default='1', max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
